CREATE TABLE product (
    productID VARCHAR(50) PRIMARY KEY,
    bleachingCode INT,
    defaultLanguage VARCHAR(10),
    dryCleaningCode INT,
    dryingCode INT,
    fasteningTypeCode INT,
    ironingCode INT,
    pulloutTypeCode INT,
    sapPacket INT,
    updateImages BOOLEAN,
    waistlineCode INT,
    washabilityCode INT
);

CREATE TABLE details_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    productID VARCHAR(50),
    cedi VARCHAR(10),
    childWeightFrom DECIMAL(5, 2),
    childWeightTo DECIMAL(5, 2),
    color_code VARCHAR(10),
    color_description VARCHAR(255),
    countryImages BOOLEAN,
    defaultSku BOOLEAN,
    preferredEan VARCHAR(20),
    sapAssortmentLevel VARCHAR(10),
    sapPrice DECIMAL(8, 2),
    season VARCHAR(10),
    showOnLineSku BOOLEAN,
    size_code VARCHAR(10),
    size_description VARCHAR(255),
    skuID VARCHAR(20),
    skuName VARCHAR(255),
    stateOfArticle BOOLEAN,
    umSAPprice VARCHAR(10),
    volume DECIMAL(10, 2),
    weight DECIMAL(8, 2),
    FOREIGN KEY (productID) REFERENCES product(productID)
);

CREATE TABLE header_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    productID VARCHAR(50),
    bag BOOLEAN,
    bleachingDescription VARCHAR(255),
    brand VARCHAR(255),
    brandCode INT,
    catalog VARCHAR(255),
    composition VARCHAR(255),
    creationDateInDatabase DATETIME,
    custom1 VARCHAR(255),
    custom2 VARCHAR(255),
    custom3 VARCHAR(255),
    drinkHolder BOOLEAN,
    dryCleaningDescription VARCHAR(255),
    dryingDescription VARCHAR(255),
    EShopDisplayName VARCHAR(255),
    EShopLongDescription TEXT,
    ergonomicSeat BOOLEAN,
    fasteningTypeDescription VARCHAR(255),
    fasteningTypeTextile VARCHAR(255),
    flat BOOLEAN,
    freeDelivery BOOLEAN,
    gender VARCHAR(50),
    indicatorOfItHasToBeAssembled BOOLEAN,
    ironingDescription VARCHAR(255),
    lastDateChanged DATETIME,
    lastUserChanged VARCHAR(255),
    productFeatures VARCHAR(255),
    productMissingFeatures VARCHAR(255),
    productStatus VARCHAR(255),
    pulloutType VARCHAR(255),
    pulloutTypeDescription VARCHAR(255),
    punnet BOOLEAN,
    sapCategoryID VARCHAR(10),
    sapCategoryName VARCHAR(255),
    sapDivisionID VARCHAR(10),
    sapDivisionName VARCHAR(255),
    sapFamilyDescription VARCHAR(255),
    sapFamilyID VARCHAR(10),
    sapFamilyName VARCHAR(255),
    sapMacrocategoryID VARCHAR(10),
    sapMacrocategoryName VARCHAR(255),
    sapName VARCHAR(255),
    sapUniverseID VARCHAR(10),
    sapUniverseName VARCHAR(255),
    showOnLine BOOLEAN,
    sizeGuide VARCHAR(50),
    sourceID VARCHAR(255),
    userOfCreation VARCHAR(255),
    waistlineDescription VARCHAR(255),
    washability VARCHAR(255),
    washabilityDescription VARCHAR(255),
    zipStopper BOOLEAN,
    FOREIGN KEY (productID) REFERENCES product(productID)
);
